import express from 'express';
import { query } from '../database/connection.js';
import { authenticateToken, requireDealerAccess } from '../middleware/auth.js';

const router = express.Router();

router.use(authenticateToken);
router.use(requireDealerAccess);

/**
 * GET /api/marbalism/stats
 * Returns per-agent stats + summary for the authenticated dealer.
 * Reads from: crew_ai_agent_assignments, crew_ai_agent_performance, daive_conversations, leads
 */
router.get('/stats', async (req, res) => {
  try {
    const dealerId = req.user.dealer_id;

    // Per-agent stats: conversations handled and leads generated by Marbalism agent types
    const agentStatsResult = await query(
      `SELECT
         caa.agent_type,
         COUNT(DISTINCT dc.id)::int                   AS total_conversations,
         COUNT(DISTINCT l.id)::int                    AS leads_generated,
         COALESCE(AVG(dc.lead_qualification_score), 0) AS avg_score
       FROM crew_ai_agent_assignments caa
       LEFT JOIN daive_conversations dc
         ON dc.dealer_id = caa.dealer_id
        AND dc.agent_type = caa.agent_type
       LEFT JOIN leads l
         ON l.id = dc.lead_id
        AND l.dealer_id = caa.dealer_id
       WHERE caa.dealer_id = $1
         AND caa.agent_type LIKE 'marbalism%'
       GROUP BY caa.agent_type`,
      [dealerId]
    );

    // Summary totals for this dealer
    const summaryResult = await query(
      `SELECT
         COUNT(DISTINCT dc.id)::int                   AS total_conversations,
         COUNT(DISTINCT l.id)::int                    AS total_leads,
         COALESCE(AVG(dc.lead_qualification_score), 0) AS avg_qualification
       FROM daive_conversations dc
       LEFT JOIN leads l
         ON l.id = dc.lead_id
        AND l.dealer_id = dc.dealer_id
       WHERE dc.dealer_id = $1
         AND dc.agent_type LIKE 'marbalism%'`,
      [dealerId]
    );

    res.json({
      agents: agentStatsResult.rows,
      summary: summaryResult.rows[0] || { total_conversations: 0, total_leads: 0, avg_qualification: 0 },
    });
  } catch (error) {
    console.error('Marbalism stats error:', error);
    res.status(500).json({ error: 'Failed to fetch Marbalism stats' });
  }
});

/**
 * GET /api/marbalism/conversations?limit=20&offset=0
 * Returns recent conversations handled by Marbalism agents for this dealer.
 */
router.get('/conversations', async (req, res) => {
  try {
    const dealerId = req.user.dealer_id;
    const limit = Math.min(parseInt(req.query.limit) || 20, 50);
    const offset = parseInt(req.query.offset) || 0;

    const result = await query(
      `SELECT
         dc.id,
         dc.customer_name,
         dc.customer_email,
         dc.lead_status,
         dc.lead_qualification_score,
         dc.agent_type,
         dc.handoff_requested,
         dc.lead_id,
         dc.vehicle_id,
         dc.created_at,
         dc.updated_at
       FROM daive_conversations dc
       WHERE dc.dealer_id = $1
         AND dc.agent_type LIKE 'marbalism%'
       ORDER BY dc.created_at DESC
       LIMIT $2 OFFSET $3`,
      [dealerId, limit, offset]
    );

    res.json({ conversations: result.rows });
  } catch (error) {
    console.error('Marbalism conversations error:', error);
    res.status(500).json({ error: 'Failed to fetch Marbalism conversations' });
  }
});

/**
 * POST /api/marbalism/chat
 * Entry point for a Marbalism agent conversation turn.
 * Reads: vehicles (inventory), daive_conversations (history)
 * Writes: daive_conversations (score, status), leads (on qualification)
 */
router.post('/chat', async (req, res) => {
  try {
    const dealerId = req.user.dealer_id;
    const { session_id, message, agent_type = 'marbalism_sales', customer_name, customer_email } = req.body;

    if (!session_id || !message) {
      return res.status(400).json({ error: 'session_id and message are required' });
    }

    // Verify dealer has Marbalism AI enabled
    const dealerResult = await query(
      'SELECT marbalism_ai_enabled, business_name FROM dealers WHERE id = $1',
      [dealerId]
    );

    if (!dealerResult.rows[0]?.marbalism_ai_enabled) {
      return res.status(403).json({ error: 'Marbalism AI is not enabled for this dealer' });
    }

    // Get or create the conversation record
    let conversationResult = await query(
      `SELECT * FROM daive_conversations WHERE session_id = $1 AND dealer_id = $2`,
      [session_id, dealerId]
    );

    let conversation;
    if (conversationResult.rows.length === 0) {
      // New conversation
      const insertResult = await query(
        `INSERT INTO daive_conversations
           (dealer_id, session_id, agent_type, customer_name, customer_email,
            lead_status, lead_qualification_score, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, 'new', 0, NOW(), NOW())
         RETURNING *`,
        [dealerId, session_id, agent_type, customer_name || null, customer_email || null]
      );
      conversation = insertResult.rows[0];
    } else {
      conversation = conversationResult.rows[0];
    }

    // Fetch dealer's live vehicle inventory for context (top 20 available vehicles)
    const vehiclesResult = await query(
      `SELECT id, year, make, model, trim, price, mileage, status, color, vin
       FROM vehicles
       WHERE dealer_id = $1 AND status = 'available' AND price > 0
       ORDER BY created_at DESC
       LIMIT 20`,
      [dealerId]
    );
    const inventory = vehiclesResult.rows;

    // Save the incoming user message
    await query(
      `INSERT INTO conversation_messages
         (conversation_id, role, content, created_at)
       VALUES ($1, 'user', $2, NOW())`,
      [conversation.id, message]
    );

    // Basic intent scoring: bump qualification score for buying signals
    const buyingSignals = ['price', 'buy', 'purchase', 'afford', 'test drive', 'financing', 'deal', 'interested', 'available'];
    const signalHits = buyingSignals.filter((s) => message.toLowerCase().includes(s)).length;
    const newScore = Math.min(100, (conversation.lead_qualification_score || 0) + signalHits * 10);

    const updatedStatus = newScore >= 70 ? 'hot' : newScore >= 40 ? 'warm' : 'new';

    // Update conversation with new score
    await query(
      `UPDATE daive_conversations
       SET lead_qualification_score = $1,
           lead_status = $2,
           customer_name = COALESCE($3, customer_name),
           customer_email = COALESCE($4, customer_email),
           updated_at = NOW()
       WHERE id = $5`,
      [newScore, updatedStatus, customer_name || null, customer_email || null, conversation.id]
    );

    // Auto-create a lead if score crosses 70 and no lead exists yet
    let leadCreated = false;
    if (newScore >= 70 && !conversation.lead_id && (customer_name || customer_email)) {
      try {
        const leadResult = await query(
          `INSERT INTO leads
             (dealer_id, customer_name, customer_email, message, status, interest_level, created_at, updated_at)
           VALUES ($1, $2, $3, $4, 'hot', 'high', NOW(), NOW())
           RETURNING id`,
          [
            dealerId,
            customer_name || conversation.customer_name || 'Marbalism Lead',
            customer_email || conversation.customer_email || null,
            `Auto-qualified by Marbalism ${agent_type} agent. Score: ${newScore}`,
          ]
        );

        const leadId = leadResult.rows[0].id;
        await query(
          `UPDATE daive_conversations SET lead_id = $1, updated_at = NOW() WHERE id = $2`,
          [leadId, conversation.id]
        );
        leadCreated = true;
      } catch (leadErr) {
        console.error('Marbalism: failed to auto-create lead:', leadErr);
      }
    }

    // Build a simple contextual reply (replace with full LLM call as needed)
    const dealerName = dealerResult.rows[0].business_name;
    let reply = `Hi! I'm your ${dealerName} Marbalism AI assistant. `;

    if (inventory.length > 0 && message.toLowerCase().match(/car|vehicle|suv|truck|sedan/)) {
      const sample = inventory.slice(0, 3).map((v) => `${v.year} ${v.make} ${v.model} ($${v.price?.toLocaleString()})`).join(', ');
      reply += `We currently have these vehicles available: ${sample}. Would you like more details on any of them?`;
    } else {
      reply += `How can I help you find your perfect vehicle today?`;
    }

    // Save AI reply
    await query(
      `INSERT INTO conversation_messages
         (conversation_id, role, content, created_at)
       VALUES ($1, 'assistant', $2, NOW())`,
      [conversation.id, reply]
    );

    res.json({
      reply,
      session_id,
      conversation_id: conversation.id,
      qualification_score: newScore,
      lead_status: updatedStatus,
      lead_created: leadCreated,
      inventory_count: inventory.length,
    });
  } catch (error) {
    console.error('Marbalism chat error:', error);
    res.status(500).json({ error: 'Marbalism AI chat failed' });
  }
});

export default router;
